export {default as Header} from "./header/Header"
export {default as Services} from "./services/Services"
export {default as Projects} from "./projects/Projects"
export {default as Contact} from "./contact/Contact"
export {default as Offer} from "./offer/Offer"
export {default as ContactUs} from "./contact_us/ContactUs"